# Generated by Django 3.0.7 on 2020-06-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_auto_20200604_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax',
            field=models.FloatField(choices=[(0, 'NIL'), (12, 12), (16, 16)], null=True),
        ),
    ]
